# Single run for balanced class_weight
time python ../predict_main.py --target transfus_yes --period='PI' --infile ../../../data/csl/CSL_ty_PI.csv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_PI_Ty_coeff_Union50.csv --feats='Union50' --under_alg='NONE' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[128],"criterion":["gini"],"max_depth":[40],"min_samples_leaf":[1],"min_samples_split":[2],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["balanced","None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output

time python ../predict_main.py --target transfus_yes --period='PI' --infile ../../../data/csl/CSL_ty_PI.csv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_PI_Ty_coeff_Union50.csv --feats='Union50' --under_alg='NONE' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[32,128,512],"criterion":["gini"],"max_depth":[20,40,80],"min_samples_leaf":[1],"min_samples_split":[2],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["balanced","None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output

time python ../predict_main.py --target transfus_yes --period='PI' --infile ../../../data/csl/CSL_ty_PI.csv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_PI_Ty_coeff_ALL.csv --feats='ALL' --under_alg='RAND' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[32,128,512],"criterion":["gini"],"max_depth":[20,40,80],"min_samples_leaf":[1],"min_samples_split":[2],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output

time python ../predict_main.py --target transfus_yes --period='Pre' --infile ../../../data/csl/CSL_ty_Pre.csv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_Pre_Ty_coeff_Union50.csv --feats='Union50' --under_alg='RAND' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[32,128,512],"criterion":["gini"],"max_depth":[20,40,80],"min_samples_leaf":[16],"min_samples_split":[2],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output

time python ../predict_main.py --target transfus_yes --period='Pre' --infile ../../../data/csl/CSL_ty_Pre.csv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_Pre_Ty_coeff_ALL.csv --feats='ALL' --under_alg='RAND' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[32,128,512],"criterion":["gini"],"max_depth":[20,40,80],"min_samples_leaf":[16],"min_samples_split":[4,16],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output

------------
trans_loss
------------
time python ../predict_main.py --target trans_loss --period='PI' --infile ../../../data/csl/CSL_tl_PI.csv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_PI_Tl_coeff_Union50.csv --feats='Union50' --under_alg='RAND' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[32,128,512],"criterion":["gini"],"max_depth":[20,40,80],"min_samples_leaf":[1],"min_samples_split":[2],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output

time python ../predict_main.py --target trans_loss --period='PI' --infile ../../../data/csl/CSL_tl_PI.csv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_PI_Tl_coeff_ALL.csv --feats='ALL' --under_alg='RAND' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[32,128,512],"criterion":["gini"],"max_depth":[20,40,80],"min_samples_leaf":[16],"min_samples_split":[2],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output

time python ../predict_main.py --target trans_loss --period='Pre' --infile ../../../data/csl/CSL_tl_Pre.csv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_Pre_Tl_coeff_Union50.csv --feats='Union50' --under_alg='RAND' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[32,128,512],"criterion":["gini"],"max_depth":[20,40,80],"min_samples_leaf":[16],"min_samples_split":[4,16],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output

time python ../predict_main.py --target trans_loss --period='Pre' --infile ../../../data/csl/CSL_tl_Pre.csv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_Pre_Tl_coeff_ALL.csv --feats='ALL' --under_alg='RAND' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[32,128,512],"criterion":["gini"],"max_depth":[20,40,80],"min_samples_leaf":[16],"min_samples_split":[4,16],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output

----------------
Under_alg = NONE
----------------
time python ../predict_main.py --target transfus_yes --period='PI' --infile ../../../data/csl/CSL_ty_PI.csvsv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_PI_Ty_coeff_Union50.csv --feats='Union50' --under_alg='NONE' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[32,128,512],"criterion":["gini"],"max_depth":[20,40,80],"min_samples_leaf":[1],"min_samples_split":[2],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output

time python ../predict_main.py --target trans_loss --period='PI' --infile ../../../data/csl/CSL_tl_PI.csv --pred_alg RF --corr_var_file ../../../data/csl/CramerTheil/Cramer_PI_Ty_coeff_Union50.csv --feats='Union50' --under_alg='NONE' --samp_strat 1.0 --sample_tts 0 --feature_thresh 1.0 --pred_params '[{"n_estimators":[32,128,512],"criterion":["gini"],"max_depth":[20,40,80],"min_samples_leaf":[1],"min_samples_split":[2],"max_leaf_nodes":[100],"max_features":["auto"],"class_weight":["None"],"random_state":[7]}]' --nproc 1 --seed 3 --output_dir ./output
